version: "3.5"
services:

  server-app:
    image: php:8.1-rc-fpm
    ports:
      - 8909:80
        # volume:
        #   type: bind
        #   source: 
        #   target:

  server-web:
    image: nginx:latest
    ports:
      - 8765:80
        # volume:
        #   type: bind
        #   source:
        #   target:

  client:
    image: php:7.3.29-apache

  redis:
    image: redis:latest
    ports:
      - 6379:6379
        # volumes:
        #   type: bind
        #   source: ./docker/redis/data
        #   target: /data

